CREATE TABLE IF NOT EXISTS Employee (
    EmployeeId INT NOT NULL AUTO_INCREMENT,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    MiddleName VARCHAR(255) NOT NULL,
    Age INT NOT NULL,
    BirthDate TIMESTAMP NOT NULL,
    HireDate TIMESTAMP NOT NULL,
    Gender VARCHAR(255) NOT NULL,
    MaritalStatus VARCHAR(255) NOT NULL,
    CurrentPosition VARCHAR(255) NOT NULL,
    CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    UpdatedOn DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (EmployeeId)
);
