CREATE TABLE IF NOT EXISTS Employee (
    EmployeeId INT NOT NULL AUTO_INCREMENT,
    FirstName VARCHAR(255),
    LastName VARCHAR(255),
    MiddleName VARCHAR(255),
    Age INT,
    BirthDate TIMESTAMP,
    HireDate TIMESTAMP,
    Gender VARCHAR(255),
    MaritalStatus VARCHAR(255),
    CurrentPosition VARCHAR(255),
    CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    UpdatedOn DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (EmployeeId)
);
