CREATE TABLE IF NOT EXISTS User (
    UserId INT NOT NULL AUTO_INCREMENT,
    Username VARCHAR(255) NOT NULL,
    Hash VARCHAR(1000) NOT NULL,
    Roles VARCHAR(100) NOT NULL,
    CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedOn DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (UserId)
);
