services:
  employee-service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - employee-service-network
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/legalmatch?allowPublicKeyRetrieval=true
    depends_on:
      mysqldb:
        condition: service_healthy
    links:
      - mysqldb
    volumes:
      - .m2:/root/.m2
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - employee-service-network
    environment:
      MYSQL_DATABASE: legalmatch
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: test_pw
      MYSQL_ROOT_PASSWORD: test_pw
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  employee-service-network:
